image: python:3.9

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test
  - linting


before_script:
  - python --version  # For debugging
  - pip3 install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install pre-commit
  - pip install isort
  - pip install black==23.1.0
  - pip install flake8
  - pip install pytest
  - pip install pylint
  - pip install -r requirements.txt
  - pip install networkx[default]
  - pip install -e .
  - pip install networkit
  - python -m pip install -e ./

isort:
  stage: linting
  script:
    - isort .

black:
  stage: linting
  script:
    - black --check src/
    - black --check tests/

flake8:
  stage: linting
  script:
    - flake8 src/
    - flake8 tests/

pylint:
  stage: linting
  script:
    - pylint src/

python_test:
    stage: test
    script:
        #- venv install
        - python -m pytest